name: izaleu
favicon: null
layout_spectrum: 0.7388559945393354
typography_spectrum: 0.11153523460961878
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.12955654389224946
  lightness: 0.2456148553173989
  saturation: 0.9848499682266265
  rhythmicContrast: 0.19638899038545787
purpose: []
